= #table(
    {"файл", "листы", "содержимое", "ссылка", "скачать в excel"},
    {
        {
            "справочник", 
            "персонал;
            проект;
            договор;
            организация", 
            "справочники для статусов",
            "https://docs.google.com/spreadsheets/d/1WyM00ui1G3MgvEncRO4yc_Co6E0aLrTBsmPgWo0rQYU/edit?usp=sharing", 
            "https://docs.google.com/spreadsheets/d/1WyM00ui1G3MgvEncRO4yc_Co6E0aLrTBsmPgWo0rQYU/export?format=xlsx"
        },
        {
            "календарь",
            "календарь",
            "справочник с календарем",
            "https://docs.google.com/spreadsheets/d/e/2PACX-1vSJrBDSBYm1bG711ZQLia3PGbvf7pKAuCSqof-PkuzjlCgju5tN6w946M2yxT2g1QHRKSqRdwUtCvxI/pubhtml",
            "https://docs.google.com/spreadsheets/d/e/2PACX-1vSJrBDSBYm1bG711ZQLia3PGbvf7pKAuCSqof-PkuzjlCgju5tN6w946M2yxT2g1QHRKSqRdwUtCvxI/pub?output=xlsx"
        }/*,
        {
            "статус вкс", 
            "dd/mm/yyyy",
            "статус формирования вкс по месяцам",
            "https://docs.google.com/spreadsheets/d/1H6kGqe1T-MjuLijTOUDu-oVYS9lA08-MivwKF486A-M/edit?usp=sharing",
            "https://docs.google.com/spreadsheets/d/1H6kGqe1T-MjuLijTOUDu-oVYS9lA08-MivwKF486A-M/export?format=xlsx"
        },
        {
            "статус ет1", 
            "dd/mm/yyyy_#_декада",
            "статус согласования ет1 по декадам",
            "https://docs.google.com/spreadsheets/d/1jBCwy0j8A6tdhj6Dkg4nTBD4C7Nejkpds7y2Mk-Dz5s/edit?usp=sharing",
            "https://docs.google.com/spreadsheets/d/1jBCwy0j8A6tdhj6Dkg4nTBD4C7Nejkpds7y2Mk-Dz5s/export?format=xlsx"
        },
        {
            "статус влр", 
            "dd/mm/yyyy",
            "статус согласования влр по месяцам",
            "https://docs.google.com/spreadsheets/d/1Uf72uy-Hdq6GiueGrQkW1ukS_9QbB6rm-0ygDhBSm2A/edit?usp=sharing",
            "https://docs.google.com/spreadsheets/d/1Uf72uy-Hdq6GiueGrQkW1ukS_9QbB6rm-0ygDhBSm2A/export?format=xlsx"
        }*/
    }
)